env:
  browser: true
  es2021: true
extends: google
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'max-len': ['error', { 'code': 185 }],
  'object-curly-spacing': ['error', 'never'],
  'valid-jsdoc': 'off',
  'require-jsdoc': 'off',
  'new-cap': 'off',
  "no-mixed-spaces-and-tabs": 0,
  "semi": "off",
}
